---
# @author: Johan Barón
# @email: johan.baron@entelgy.com
# Playbooks to ping windows hosts


- name: Install dependencies
  hosts: tower
  become: yes

  tasks:
    - name: install local dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python-devel
        - krb5-devel
        - krb5-libs
        - krb5-workstation
        - python-pip
        - gcc
        - python2-winrm.noarch

          #- name: PLAY Wingping
          #  hosts: windows

#  roles:
#    - role: 
#      become: yes
  
          #  tasks:
          #    - name: to ping
          #      win_ping:

