---
# @author: Johan Barón
# @email: johan.baron@entelgy.com
# Playbooks to ping windows hosts

- name: PLAY Wingping
  hosts: windows
  gather_facts: false

  tasks:
  - name: to ping
    win_ping:

